parameters:
    btn_base.twig.file_size.class: Btn\BaseBundle\Twig\FileSizeExtension
    btn_base.twig.csrf_path.class:  Btn\BaseBundle\Twig\CsrfPathExtension
    btn_base.twig.assetic.class: Btn\BaseBundle\Twig\AsseticExtension

services:
    btn_base.twig.file_size:
        class: %btn_base.twig.file_size.class%
        tags:
            - { name: twig.extension }

    btn_base.twig.csrf_path:
        class:  %btn_base.twig.csrf_path.class%
        arguments:
            router: @router
            csrfProvider: @form.csrf_provider
        tags:
            - { name: twig.extension }

    btn_base.twig.assetic:
        class: %btn_base.twig.assetic.class%
        arguments:
            storage: @btn_base.asset_storage
            manager: @btn_base.asset_manager
            loader: @btn_base.asset_loader
        tags:
            - { name: twig.extension }
