services:
    btn.templating:
        class: Btn\BaseBundle\Model\Templating
    btn.rest_form:
        class: Btn\BaseBundle\Model\RestForm
        arguments:
            translator: "@translator"
    btn.listener.preexecute:
        class: Btn\BaseBundle\Listener\PreExecute
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        priority: -1000
        arguments:
            resolver: "@controller_resolver"

    btn.twig.size_extension:
        class: Btn\BaseBundle\Twig\SizeExtension
        tags:
            - { name: twig.extension }

    btn.livereload_js:
        class: Btn\BaseBundle\Listener\ScriptInject
        arguments: ["%btn_base.livereload_port%", "%btn_base.livereload_enabled%"]
        tags:
            - { name: kernel.event_subscriber }
