services:

    btn_base.helper.templating:
        class: %btn_base.helper.templating.class%

    btn_base.event_listener.preexecute:
        class: %btn_base.event_listener.preexecute.class%
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        priority: -1000
        arguments: [@controller_resolver]

    btn_base.event_listener.livereload:
        class: %btn_base.event_listener.livereload.class%
        arguments: ['%btn_base.livereload.enabled%', '%btn_base.livereload.host%', '%btn_base.livereload.port%']
        tags:
            - { name: kernel.event_subscriber }

    btn_base.event_listener.doctrine_table:
        class: %btn_base.event_listener.doctrine_table.class%
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }
        arguments: [%btn_base.doctrine.table.options%]

    btn_base.twig.size_extension:
        class: %btn_base.twig.size_extension.class%
        tags:
            - { name: twig.extension }

    btn_base.twig.csrf_path_extension:
        class:  %btn_base.twig.csrf_path_extension.class%
        arguments:
            router: @router
            csrfProvider: @form.csrf_provider
        tags:
            - { name: twig.extension }
